name = "DDMServer"
uuid = "4f18b3d6-c20d-4cd4-957b-c86edd7eea66"
authors = ["Johannes Ahnlide <johannes@voxel.se> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
